### PR TITLE
feat!: generate themes from catppuccin/iterm

### PR DESCRIPTION
**Pull request by uncenter**
#1 is no longer needed with this PR, I don't think we need to include that key in the first place. This PR adds a new build system that uses a Swift script to convert each flavor from our iTerm port into a Terminal.app theme file. I took https://github.com/lysyi3m/macos-terminal-themes/blob/master/tools/iterm2terminal.swift as a base and modernized it quite a bit with what little I know about Swift. Unfortunately I don't think we can use easier tools like Deno or Whiskers for this port due to the cursed nature of the `.terminal` file format - the data for each color is a representation of Apple's `NSColor`, encoded with `NSKeyedArchiver`.

### CODE REVIEW

**Review by sgoudham — APPROVED** [review]
Looks good. Tested out the files and it seems to be correct (aside from the fact that the normal and bright are the same 😄):

Screenshot 2024-09-02 at 17 06 43

The term did automatically set my theme to `x256color` so I think it's fine ommitting it. If an issue gets raised then we think about adding it back in.

**Comment by uncenter** [comment]
We should probably set up https://github.com/sgoudham/update-git-submodules here as well on latest commit mode.

**Comment by sgoudham** [comment]
I'd rather renovate if we're going to do latest commit since that's supported by them without breaking git behaviour.

**Comment by uncenter** [comment]
Sure, that works too :)

**Pull request merged**
